// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage0":return img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f 2 f . . . 
. . . f f e e e e f 2 2 2 f . . 
. . . f e e e f f e e e e f . . 
. . . f f f f e e 2 2 2 2 e f . 
. . . f e 2 2 2 f f f f e 2 f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e 2 2 2 f . . . 
. . . . . e d d e 2 2 2 f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`;
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . f . . . . 
. . . . . . . . . . . . f . . . 
. . . f f f f f f f f f . f . . 
. . . f . . . . . . . f . . f . 
. . . f . . . . . . . f . . . f 
. . . f . . . . . . . f . . . f 
. . . f . . . . . . . f . . . f 
. . . f . . . . . . . f . . . f 
. . . f . . . . . . . f . . f . 
. . . f f f f f f f f f . f . . 
. . . . . . . . . . . . f . . . 
. . . . . . . . . . . f . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "myImage1":return img`
................................
................................
................................
................................
................................
................................
.................e22............
.................eee............
..............cbbebbc...........
.............cbbbebbc...........
............fcbdbcbbb...........
...........fccdbdcdbb...........
...........fcccdbbbbc...........
...........ccccdcbbcc...........
...........cccfbcccbb...........
...........cfffbcbbf............
...........cfffbcbf.............
..........bbbcfffb.666..........
.........bbbbdf77b77777.........
........cbbbdf766b67777c........
.........dbbdf776667766c........
..........ccf767777766cb........
...........66bb6bb66dcb.........
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
